### ISSUE TITLE
Different results in every execution

### ISSUE THREAD

**Issue by burgosmad** [YorkUCVIL/Static-Dynamic-Interpretability#3]
Hello, thanks for your interesting work. I was wondering why do I get different results every time I execute. Is it normal. I think it has relation with the pair of stylized frames taken but I am not shure.

**Comment by MKowal2** [comment]
Thank you for the kind words!

I think I see the problem, we use a random seed from the config.py file - [config.random_seed here.](https://github.com/YorkUCVIL/Static-Dynamic-Interpretability/blob/f552b31db1f34b622decc39b72206a55d800948f/config.py#L8). However, it looks like we forgot to actually use it at the beginning of the main scripts. So to fix this, just put this at the beginning of the main scripts:

```
np.random.seed(args.random_seed)
torch.manual_seed(args.random_seed)
```
